[package]
name = "navigate"
version = "0.1.0"
authors = ["Tom Jones <tomfjones8@gmail.com>"]
license = "MIT"
description = "Navigation modules in Rust"
edition = "2024"

[dependencies]
num-traits = "0.2.19"
rustc-hash = "2.1.1"
indexmap = "2.9.0"